### ISSUE TITLE
[Marketing] Website Change Request: Landing Page Heading Update

### ISSUE THREAD

**Issue by queens-wic** [queens-wic/qwic#25]
### 1. **Portfolio Name**  
_(Please select the portfolio making this request)_  
- [ ] Marketing  
- [ ] HackHer  
- [ ] Community  
- [ ] Operations
- [ ] Mentorship  
- [X] Other: (please specify)

### 2. **Request Type**  
_(What kind of request is this?)_  
- [ ] New page  
- [X] Design change  
- [ ] Content update  
- [ ] Feature request  
- [ ] Bug fix  
- [ ] Other: (please specify)

### 3. **Summary of the Request**  
_(Provide a brief description of what you are requesting)_  
Change the text on the landing page.

### 4. **Detailed Description**  
_(Provide all the necessary details, including any specific requirements, design changes, or content updates you need. If possible, include mockups, screenshots, or links to relevant materials.)_  
The current landing page:
![image](https://github.com/user-attachments/assets/dab1aece-e444-4ab0-97d8-7a252e9c7ab9)

Want changes made to the main heading to be: **_"Queen's Women in Computing"_** and the subheading to be **_"Explore Technology and Embrace Empowerment"_**

Idea of the design change: 
![image](https://github.com/user-attachments/assets/80606069-8c5c-4f22-87e9-2f5fccce9cfe)

### 5. **Priority Level**  
_(How urgent is this request?)_  
- [X] High (needed ASAP)  
- [ ] Medium (needed soon)  
- [ ] Low (nice to have, but not urgent)

### 6. **Timeline**  
_(If there's a specific deadline or target date, please mention it)_  

### 7. **Additional Information**  
_(Any other details that the team should be aware of, such as dependencies, technical requirements, etc.)_  

---

### Contact Information  
_(Who should be contacted for follow-up questions?)_

**Portfolio Contact**:  Jade (@ jadeeeewarren)

**Comment by kalefed** [comment]
## Hero Design 01
![image](https://github.com/user-attachments/assets/f7d3b120-3e95-4f83-add1-76c1567b5797)

## Hero Design 02
![image](https://github.com/user-attachments/assets/0ee76f30-470a-4d45-b42b-f595699af3a7)

**Comment by kalefed** [comment]
## Who Are We Design 01
![image](https://github.com/user-attachments/assets/c38162f6-e64a-4c16-832d-b32479f6f5b0)

## Who Are We Design 02
![image](https://github.com/user-attachments/assets/fd731f52-6ae3-4a03-826b-17346d106005)

**Comment by jadewarren** [comment]
I think it all looks great! If I had to choose I prefer the first Hero design and the second "Who we are".
